# Generated by Django 5.2 on 2025-07-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_employeeposition_customuser_employe_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='employe_position',
            new_name='employee_position',
        ),
    ]
