# Generated by Django 5.2 on 2025-07-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_rename_employe_position_customuser_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_orders', to='api1.employeeposition'),
        ),
    ]
