# Generated by Django 5.2 on 2025-07-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_travelorder_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='status',
            field=models.CharField(choices=[('Travel order is placed', 'Travel order is placed'), ('The travel order has been approved by the CSC head', 'The travel order has been approved by the CSC head'), ('The travel order has been rejected by the CSC head.', 'The travel order has been approved by the CSC head'), ('The travel order has been approved by the PO head', 'The travel order has been approved by the PO head'), ('The travel order has been rejected by the PO head.', 'The travel order has been approved by the PO head'), ('The travel order has been approved by the TMSD chief', 'The travel order has been approved by the TMSD chief'), ('The travel order has been rejected by the AFSD Chief.', 'The travel order has been approved by the AFSD Chief'), ('The travel order has been approved by the Regional Director', 'The travel order has been approved by the Regional Director'), ('The travel order has been rejected by the Regional Director', 'The travel order has been approved by the Regional Director')], default='Travel order is placed', max_length=100),
        ),
    ]
