# Generated by Django 5.2 on 2025-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0006_alter_travelorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='travel_order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
