# Generated by Django 5.2 on 2025-07-06 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0007_travelorder_travel_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('employee', 'Employee'), ('head', 'Head'), ('admin', 'Admin'), ('director', 'Director'), ('book keeper', 'book keeper'), ('accountant', 'accountant')], max_length=20),
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_of_travel', models.FileField(upload_to='liquidations/certificate_of_travel/')),
                ('certificate_of_appearance', models.FileField(upload_to='liquidations/certificate_of_appearance/')),
                ('after_travel_report', models.FileField(upload_to='liquidations/after_travel_report/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at_bookkeeper', models.DateTimeField(blank=True, null=True)),
                ('bookkeeper_comment', models.TextField(blank=True)),
                ('reviewed_at_accountant', models.DateTimeField(blank=True, null=True)),
                ('accountant_comment', models.TextField(blank=True)),
                ('is_bookkeeper_approved', models.BooleanField(null=True)),
                ('is_accountant_approved', models.BooleanField(null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('reviewed_by_accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_bookkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookkeeper_reviews', to=settings.AUTH_USER_MODEL)),
                ('travel_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation', to='api1.travelorder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_liquidations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
