# Generated by Django 5.2 on 2025-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0008_alter_customuser_user_level_liquidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('employee', 'Employee'), ('head', 'Head'), ('admin', 'Admin'), ('director', 'Director'), ('bookkeeper', 'bookkeeper'), ('accountant', 'accountant')], max_length=20),
        ),
    ]
