# Generated by Django 5.2 on 2025-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0009_alter_customuser_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
