# Generated by Django 5.2 on 2025-07-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0010_fund_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeposition',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
