# Generated by Django 5.2 on 2025-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0011_employeeposition_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
