# Generated by Django 5.2 on 2025-07-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0012_customuser_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_archived',
        ),
    ]
