# Generated by Django 5.2 on 2025-07-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0013_remove_customuser_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('Community Service Center Employee', 'Community service Center Employee'), ('Provincial Office Employee', 'Provincial Office Employee'), ('Regional Office-TMSD Employee', 'Regional Office-TMSD Employee'), ('Regional Office-AFSD Employee', 'Regional Office-AFSD Employee'), ('Regional Office-LU Employee', 'Regional Office-LU Employee'), ('CSC Head', 'CSC Head'), ('PO Head', 'PO Head'), ('TMSD Chief', 'TMSD Chief'), ('AFSD Chief', 'AFSD Chief'), ('Regional Director', 'Regional Director')], max_length=100, null=True),
        ),
    ]
