# Generated by Django 5.2 on 2025-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0016_employeesignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='specific_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
