# Generated by Django 5.2 on 2025-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0017_travelorder_specific_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
