# Generated by Django 5.2 on 2025-07-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0018_liquidation_resubmitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('urdaneta_csc', 'Urdaneta CSC'), ('sison_csc', 'Sison CSC'), ('pugo_csc', 'Pugo CSC'), ('sudipen_csc', 'Sudipen CSC'), ('tagudin_csc', 'Tagudin CSC'), ('banayoyo_csc', 'Banayoyo CSC'), ('dingras_csc', 'Dingras CSC'), ('pangasinan_po', 'Pangasinan PO'), ('ilocossur_po', 'Ilocos Sur PO'), ('ilocosnorte_po', 'Ilocos Norte PO'), ('launion_po', 'La Union PO'), ('tmsd', 'TMSD'), ('afsd', 'AFSD'), ('regional', 'Regional')], max_length=20, null=True),
        ),
    ]
