# Generated by Django 5.2 on 2025-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0020_alter_customuser_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='type_of_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('Community Service Center Employee', 'Community service Center Employee'), ('Provincial Office Employee', 'Provincial Office Employee'), ('Regional Office-TMSD Employee', 'Regional Office-TMSD Employee'), ('Regional Office-AFSD Employee', 'Regional Office-AFSD Employee'), ('Regional Office-LU Employee', 'Regional Office-LU Employee'), ('CSC Head', 'CSC Head'), ('PO Head', 'PO Head'), ('TMSD Chief', 'TMSD Chief'), ('AFSD Chief', 'AFSD Chief')], max_length=100, null=True),
        ),
    ]
