# Generated by Django 5.2 on 2025-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0021_remove_travelorder_type_of_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
