# Generated by Django 5.2 on 2025-08-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0022_alter_travelorder_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
