# Generated by Django 5.2 on 2025-08-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0023_alter_travelorder_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
