# Generated by Django 5.2 on 2025-08-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0024_travelorder_approval_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='approval_comment',
        ),
        migrations.AddField(
            model_name='signature',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api1.travelorder'),
        ),
    ]
