# Generated by Django 5.2 on 2025-08-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0025_remove_travelorder_approval_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='comment',
        ),
        migrations.AlterField(
            model_name='signature',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.travelorder'),
        ),
    ]
