# Generated by Django 5.2 on 2025-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0026_remove_signature_comment_alter_signature_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
