# Generated by Django 5.2 on 2025-08-26 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0027_signature_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
