# Generated by Django 5.2 on 2025-09-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0028_alter_travelorder_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='fund_cluster',
            field=models.CharField(blank=True, choices=[('01_RF', '01_RF'), ('07_TF', '07_TF')], max_length=10),
        ),
    ]
