# Generated by Django 5.2 on 2025-09-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0030_customuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Email verification code', max_length=6, null=True),
        ),
    ]
