# Generated by Django 5.2 on 2025-09-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0031_customuser_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
    ]
