# Generated by Django 5.2 on 2025-09-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='distance',
            field=models.IntegerField(default=1, help_text='Distance in kilometers'),
        ),
    ]
