# Generated by Django 5.2 on 2025-09-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0034_travelorder_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Pre-Audit', 'Under Pre-Audit'), ('Under Final Audit', 'Under Final Audit'), ('Ready for Claim', 'Ready for Claim'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
