# Generated by Django 5.2 on 2025-09-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0040_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='approver_selection',
            field=models.JSONField(blank=True, help_text='Selected approvers for each approval level', null=True),
        ),
    ]
