# Generated by Django 5.2 on 2025-09-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_aftertravelreport_liquidation_after_travel_report'),
        ('api1', '0041_add_approver_selection'),
    ]

    operations = [
    ]
