# Generated by Django 5.2 on 2025-09-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0042_merge_20250928_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='approver_selection',
        ),
    ]
