# Generated by Django 5.2 on 2025-09-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0043_remove_travelorder_approver_selection'),
    ]

    operations = [
        # Use raw SQL to drop the old column and add the new one
        migrations.RunSQL(
            "ALTER TABLE api1_liquidation DROP COLUMN after_travel_report;",
            reverse_sql="ALTER TABLE api1_liquidation ADD COLUMN after_travel_report varchar(100) NOT NULL DEFAULT '';"
        ),
        migrations.RunSQL(
            "ALTER TABLE api1_liquidation ADD COLUMN after_travel_report_id bigint NULL;",
            reverse_sql="ALTER TABLE api1_liquidation DROP COLUMN after_travel_report_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE api1_liquidation ADD CONSTRAINT api1_liquidation_after_travel_report_id_fk FOREIGN KEY (after_travel_report_id) REFERENCES api1_aftertravelreport(id);",
            reverse_sql="ALTER TABLE api1_liquidation DROP FOREIGN KEY api1_liquidation_after_travel_report_id_fk;"
        ),
        # Update the model state to reflect the new field
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidation', to='api1.aftertravelreport'),
        ),
    ]
