# Generated by Django 5.2 on 2025-09-29 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0044_auto_20250928_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('resubmit', 'Resubmit'), ('view', 'View'), ('download', 'Download'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update')], max_length=50)),
                ('resource_type', models.CharField(choices=[('travel_order', 'Travel Order'), ('liquidation', 'Liquidation'), ('user', 'User'), ('fund', 'Fund'), ('transportation', 'Transportation'), ('employee_position', 'Employee Position'), ('after_travel_report', 'After Travel Report'), ('notification', 'Notification'), ('system', 'System')], max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api1_auditl_user_id_ab871a_idx'), models.Index(fields=['action', 'timestamp'], name='api1_auditl_action_aabdad_idx'), models.Index(fields=['resource_type', 'timestamp'], name='api1_auditl_resourc_2ad7a2_idx')],
            },
        ),
    ]
