# Generated by Django 5.2 on 2025-09-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0045_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
    ]
