# Generated by Django 5.2 on 2025-10-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0047_backup_restore_backup_api1_backup_status_91ce86_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_accountant_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_bookkeeper_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bookkeeper_approved', 'Bookkeeper Approved'), ('bookkeeper_rejected', 'Bookkeeper Rejected'), ('accountant_approved', 'Accountant Approved'), ('accountant_rejected', 'Accountant Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_appearance_accountant_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_appearance_bookkeeper_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_appearance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bookkeeper_approved', 'Bookkeeper Approved'), ('bookkeeper_rejected', 'Bookkeeper Rejected'), ('accountant_approved', 'Accountant Approved'), ('accountant_rejected', 'Accountant Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_accountant_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_bookkeeper_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bookkeeper_approved', 'Bookkeeper Approved'), ('bookkeeper_rejected', 'Bookkeeper Rejected'), ('accountant_approved', 'Accountant Approved'), ('accountant_rejected', 'Accountant Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_type',
            field=models.CharField(choices=[('full', 'Full SQL Database Backup'), ('data_only', 'Data Only SQL Backup'), ('schema_only', 'Schema Only SQL Backup')], default='full', max_length=20),
        ),
    ]
