# Generated by Django 5.2 on 2025-10-04 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0048_liquidation_after_travel_report_accountant_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOfTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_cluster', models.CharField(blank=True, choices=[('01_RF', '01-RF'), ('07_TF', '07-TF')], max_length=10)),
                ('station', models.CharField(blank=True, choices=[('urdaneta_csc', 'Urdaneta Community Service Center'), ('sison_csc', 'Sison Community Service Center'), ('pugo_csc', 'Pugo Community Service Center'), ('sudipen_csc', 'Sudipen Community Service Center'), ('tagudin_csc', 'Tagudin Community Service Center'), ('banayoyo_csc', 'Banayoyo Community Service Center'), ('dingras_csc', 'Dingras Community Service Center'), ('pangasinan_po', 'Pangasinan Provincial Office'), ('ilocossur_po', 'Ilocos Sur Provincial Office'), ('ilocosnorte_po', 'Ilocos Norte Provincial Office'), ('regional', 'Regional Office')], max_length=50)),
                ('travel_order_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_travel_agency_head', to=settings.AUTH_USER_MODEL)),
                ('approved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_travel_approved', to=settings.AUTH_USER_MODEL)),
                ('respectfully_submitted', models.ManyToManyField(related_name='certificate_of_travel_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='certificate_of_travel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidation', to='api1.certificateoftravel'),
        ),
    ]
