# Generated by Django 5.2 on 2025-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0049_certificateoftravel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateoftravel',
            name='date_travel_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='date_travel_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
