# Generated by Django 5.2 on 2025-10-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0050_certificateoftravel_date_travel_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateoftravel',
            name='deviation_type',
            field=models.CharField(blank=True, choices=[('strictly_accordance', 'Strictly in accordance with the approved itinerary'), ('cut_short', 'Cut short as explained below. Excess payment in the amount of P_______ was refunded under O.R No._____dated_____'), ('extended', 'Extended as explained below. Additional itinerary was submitted'), ('other_deviation', 'Other deviation as explained below')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='evidence_others_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('certificate_of_travel', 'Certificate of Travel'), ('others', 'Others')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='explanations_justifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='or_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='or_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
