# Generated by Django 5.2 on 2025-10-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0051_certificateoftravel_deviation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateoftravel',
            name='deviation_type',
            field=models.CharField(blank=True, choices=[('strictly_accordance', 'Strictly in accordance with the approved itinerary'), ('cut_short_excess', 'Cut short as explained below. Excess payment in the amount of P____________'), ('cut_short_refunded', 'was refunded under O.R. No. _____________ dated _____________'), ('extended', 'Extended as explained below. Additional itinerary was submitted'), ('other_deviation', 'Other deviation as explained below')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='status',
            field=models.CharField(choices=[('Travel request is placed', 'Travel request is placed'), ('Approved by the CSC head', 'Approved by the CSC head'), ('Rejected by the CSC head.', 'Rejected by the CSC head'), ('Approved by the PO head', 'Approved by the PO head'), ('Rejected by the PO head', 'Rejected by the PO head'), ('Approved by the TMSD chief', 'Approved by the TMSD chief'), ('Rejected by the TMSD chief', 'Rejected by the TMSD chief'), ('Approved by the AFSD chief', 'Approved by the AFSD chief'), ('Rejected by the AFSD Chief', 'Rejected by the AFSD Chief'), ('Approved by the Regional Director', 'Approved by the Regional Director'), ('Rejected by the Regional Director', 'Rejected by the Regional Director')], default='Travel order is placed', max_length=100),
        ),
    ]
