# Generated by Django 5.2 on 2025-10-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0052_alter_certificateoftravel_deviation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='status',
            field=models.CharField(choices=[('Travel request is placed', 'Travel request is placed'), ('Approved by the CSC head', 'Approved by the CSC head'), ('Rejected by the CSC head.', 'Rejected by the CSC head'), ('Approved by the PO head', 'Approved by the PO head'), ('Rejected by the PO head', 'Rejected by the PO head'), ('Approved by the TMSD chief', 'Approved by the TMSD chief'), ('Rejected by the TMSD chief', 'Rejected by the TMSD chief'), ('Approved by the AFSD chief', 'Approved by the AFSD chief'), ('Rejected by the AFSD Chief', 'Rejected by the AFSD Chief'), ('Approved by the Regional Director', 'Approved by the Regional Director'), ('Rejected by the Regional Director', 'Rejected by the Regional Director')], default='Travel request is placed', max_length=100),
        ),
    ]
