# Generated by Django 5.2 on 2025-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0053_alter_travelorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='True if this is a draft, False if submitted'),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Under Pre-Audit', 'Under Pre-Audit'), ('Under Final Audit', 'Under Final Audit'), ('Ready for Claim', 'Ready for Claim'), ('Rejected', 'Rejected')], default='Draft', max_length=50),
        ),
    ]
