# Generated by Django 5.2 on 2025-10-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0054_liquidation_is_draft_alter_liquidation_status'),
    ]

    operations = [
    ]
