# Generated by Django 5.2 on 2025-10-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0056_remove_liquidation_is_draft_alter_liquidation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aftertravelreport',
            name='attachments',
        ),
    ]
