# Generated by Django 5.2 on 2025-10-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0057_remove_aftertravelreport_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateoftravel',
            name='deviation_type',
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='deviation_types',
            field=models.JSONField(default=list, help_text='List of selected deviation types'),
        ),
    ]
