# Generated by Django 5.2 on 2025-10-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0058_remove_certificateoftravel_deviation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateoftravel',
            name='evidence_others_description',
        ),
    ]
