# Generated by Django 5.2 on 2025-10-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0059_remove_certificateoftravel_evidence_others_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateoftravel',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('certificate_of_appearance', 'Certificate of Appearance'), ('others', 'Others')], max_length=25, null=True),
        ),
    ]
