# Generated by Django 5.2 on 2025-10-08 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0060_alter_certificateoftravel_evidence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_travel_report_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_travel_report_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_reviewer_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_reviewer_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_travel_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_travel_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_reviewer_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_reviewer_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='after_travel_report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_review', 'Pending Review'), ('reviewer_approved', 'Reviewer Approved'), ('reviewer_rejected', 'Reviewer Rejected'), ('bookkeeper_approved', 'Bookkeeper Approved'), ('bookkeeper_rejected', 'Bookkeeper Rejected'), ('accountant_approved', 'Accountant Approved'), ('accountant_rejected', 'Accountant Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='certificate_of_travel_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_review', 'Pending Review'), ('reviewer_approved', 'Reviewer Approved'), ('reviewer_rejected', 'Reviewer Rejected'), ('bookkeeper_approved', 'Bookkeeper Approved'), ('bookkeeper_rejected', 'Bookkeeper Rejected'), ('accountant_approved', 'Accountant Approved'), ('accountant_rejected', 'Accountant Rejected')], default='pending', max_length=20),
        ),
    ]
