# Generated by Django 5.2 on 2025-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0061_liquidation_after_travel_report_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='barangay_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='barangay_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='city_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='province_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='province_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='destination',
            field=models.CharField(blank=True, help_text='Computed from location fields', max_length=255, null=True),
        ),
    ]
