# Generated by Django 5.2 on 2025-10-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0062_travelorder_barangay_code_travelorder_barangay_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='barangay_code',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='barangay_name',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='province_code',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='province_name',
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='destination',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
