# Generated by Django 5.2 on 2025-10-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0063_remove_travelorder_barangay_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='approver_selection',
            field=models.JSONField(blank=True, default=dict, help_text='Selected approvers for each level in the approval chain'),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='prepared_by_position_name',
            field=models.CharField(blank=True, help_text='Position name of the person who prepared the travel order', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='prepared_by_user_type',
            field=models.CharField(blank=True, help_text='Type of user who prepared the travel order', max_length=100, null=True),
        ),
    ]
