# Generated by Django 5.2 on 2025-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0064_travelorder_approver_selection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesignature',
            name='signature_data',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='signature_data',
        ),
        migrations.AddField(
            model_name='employeesignature',
            name='signature_photo',
            field=models.FileField(blank=True, null=True, upload_to='signatures/employee/'),
        ),
        migrations.AddField(
            model_name='signature',
            name='signature_photo',
            field=models.FileField(blank=True, null=True, upload_to='signatures/head/'),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='after_travel_report_reviewer_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/liquidation/after_travel/'),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='certificate_of_travel_reviewer_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/liquidation/certificate_of_travel/'),
        ),
    ]
