# Generated by Django 5.2 on 2025-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0065_remove_employeesignature_signature_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('Community Service Center Employee', 'Community service Center Employee'), ('Provincial Office Employee', 'Provincial Office Employee'), ('Regional Office-TMSD Employee', 'Regional Office-TMSD Employee'), ('Regional Office-AFSD Employee', 'Regional Office-AFSD Employee'), ('Regional Office-LU Employee', 'Regional Office-LU Employee'), ('CSC Head', 'CSC Head'), ('PO Head', 'PO Head'), ('TMSD Chief', 'TMSD Chief'), ('AFSD Chief', 'AFSD Chief'), ('Regional Director', 'Regional Director'), ('Bookkeeper', 'Bookkeeper'), ('Accountant', 'Accountant')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('employee', 'Employee'), ('head', 'Head'), ('admin', 'Admin'), ('director', 'Director'), ('bookkeeper', 'Bookkeeper'), ('accountant', 'Accountant')], max_length=20),
        ),
    ]
