# Generated by Django 5.2 on 2025-10-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0066_alter_customuser_type_of_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='official_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
