# Generated by Django 5.2 on 2025-10-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0067_travelorder_official_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='approver_position',
            field=models.JSONField(blank=True, default=dict, help_text='Positions for each approver level in the approval chain'),
        ),
    ]
