# Generated by Django 5.2 on 2025-10-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0068_travelorder_approver_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('travel_approved', 'Travel Request Approved'), ('travel_rejected', 'Travel Request Rejected'), ('travel_rejected_by_next_approver', 'Travel Request Rejected by Next Approver'), ('travel_final_approved', 'Travel Request Finally Approved'), ('new_approval_needed', 'New Approval Needed'), ('liquidation_approved', 'Liquidation Approved'), ('liquidation_rejected', 'Liquidation Rejected'), ('component_approved', 'Component Approved'), ('component_rejected', 'Component Rejected')], max_length=50),
        ),
    ]
