# Generated by Django 5.2 on 2025-10-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0070_barangay_city_province_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_destinations', to='api1.barangay'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_destinations', to='api1.city'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_destinations', to='api1.province'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_destinations', to='api1.region'),
        ),
    ]
