# Generated by Django 5.2 on 2025-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0071_itinerary_barangay_itinerary_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='city',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='province',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='region',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='province',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='region',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('travel_approved', 'Travel Request Approved'), ('travel_rejected', 'Travel Request Rejected'), ('travel_rejected_by_next_approver', 'Travel Request Rejected by Next Approver'), ('travel_final_approved', 'Travel Request Finally Approved'), ('new_approval_needed', 'New Approval Needed'), ('liquidation_approved', 'Liquidation Approved'), ('liquidation_rejected', 'Liquidation Rejected'), ('liquidation_submitted', 'Liquidation Submitted'), ('liquidation_needs_review', 'Liquidation Needs Review'), ('liquidation_deadline_approaching', 'Liquidation Deadline Approaching'), ('liquidation_expired', 'Liquidation Expired'), ('component_approved', 'Component Approved'), ('component_rejected', 'Component Rejected')], max_length=50),
        ),
    ]
