# Generated by Django 5.2 on 2025-10-13 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0072_remove_psgc_destination_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transportation Allowance'),
        ),
    ]
