# Generated by Django 5.2 on 2025-10-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0073_alter_itinerary_transportation_allowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOrderApprovalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_stage', models.IntegerField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_data', models.JSONField(default=dict, help_text='Snapshot of travel order data when approved')),
                ('approved_itineraries', models.JSONField(default=list, help_text='Snapshot of itineraries when approved')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_snapshots', to='api1.travelorder')),
            ],
        ),
    ]
