# Generated by Django 5.2 on 2025-10-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0074_travelorderapprovalsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='liquidation_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for liquidation submission', null=True),
        ),
    ]
