# Generated by Django 5.2 on 2025-10-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0075_add_liquidation_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='liquidation_deadline',
        ),
        migrations.AddField(
            model_name='liquidation',
            name='liquidation_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for liquidation completion', null=True),
        ),
    ]
