# Generated by Django 5.2 on 2025-10-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0076_add_liquidation_deadline_to_liquidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='barangay_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='province',
            name='province_code',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_code',
        ),
    ]
