# Generated by Django 5.2.7 on 2025-10-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0077_remove_psgc_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
