# Generated by Django 5.2.7 on 2025-10-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0078_auto_20251022_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(unique=True, verbose_name='email address'),
        ),
    ]
