# Generated by Django 5.2.7 on 2025-10-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0079_auto_20251022_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type_of_user',
        ),
    ]
