# Generated by Django 5.2.7 on 2025-10-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0080_auto_20251022_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
    ]
