# Generated by Django 5.2.7 on 2025-10-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0082_add_temporary_password_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='destination_cluster',
            field=models.CharField(blank=True, choices=[('Cluster I', 'Cluster I'), ('Cluster II', 'Cluster II'), ('Cluster III', 'Cluster III')], max_length=20, null=True),
        ),
    ]
