# Generated by Django 5.2.7 on 2025-10-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0083_itinerary_destination_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='region',
            field=models.CharField(blank=True, choices=[('Region I', 'Region I'), ('Region II', 'Region II'), ('Region III', 'Region III'), ('Region V', 'Region V'), ('Region VIII', 'Region VIII'), ('Region IX', 'Region IX'), ('Region XII', 'Region XII'), ('Region XIII', 'Region XIII'), ('ARMM', 'ARMM'), ('CAR', 'CAR'), ('Region VI', 'Region VI'), ('Region VII', 'Region VII'), ('Region X', 'Region X'), ('Region XI', 'Region XI'), ('NCR', 'NCR'), ('Region IV-A', 'Region IV-A'), ('Region IV-B', 'Region IV-B')], max_length=20, null=True),
        ),
    ]
