# Generated by Django 5.2.7 on 2025-10-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0085_alter_itinerary_other_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this is a draft, False if submitted for approval'),
        ),
    ]
