# Generated by Django 5.2.7 on 2025-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0086_travelorder_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
