# Generated by Django 5.2.7 on 2025-10-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0087_alter_itinerary_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='date_travel_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='date_travel_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
