# Generated by Django 5.2.7 on 2025-10-29 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0088_alter_travelorder_date_travel_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftertravelreport',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this is a draft, False if submitted for approval'),
        ),
        migrations.AddField(
            model_name='aftertravelreport',
            name='travel_order',
            field=models.ForeignKey(blank=True, help_text='Travel order this draft belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_after_travel_reports', to='api1.travelorder'),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this is a draft, False if submitted for approval'),
        ),
        migrations.AddField(
            model_name='certificateoftravel',
            name='travel_order',
            field=models.ForeignKey(blank=True, help_text='Travel order this draft belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_certificate_of_travel', to='api1.travelorder'),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='actual_output',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='cash_advance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='date_of_submission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='highlights_of_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='pap',
            field=models.CharField(blank=True, help_text='Program/Activity/Project', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='period_of_implementation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='prepared_by',
            field=models.ManyToManyField(blank=True, related_name='prepared_after_travel_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aftertravelreport',
            name='ways_forward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificateoftravel',
            name='deviation_types',
            field=models.JSONField(blank=True, default=list, help_text='List of selected deviation types'),
        ),
        migrations.AlterField(
            model_name='certificateoftravel',
            name='fund_cluster',
            field=models.CharField(blank=True, choices=[('01_RF', '01-RF'), ('07_TF', '07-TF')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificateoftravel',
            name='respectfully_submitted',
            field=models.ManyToManyField(blank=True, related_name='certificate_of_travel_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificateoftravel',
            name='station',
            field=models.CharField(blank=True, choices=[('urdaneta_csc', 'Urdaneta Community Service Center'), ('sison_csc', 'Sison Community Service Center'), ('pugo_csc', 'Pugo Community Service Center'), ('sudipen_csc', 'Sudipen Community Service Center'), ('tagudin_csc', 'Tagudin Community Service Center'), ('banayoyo_csc', 'Banayoyo Community Service Center'), ('dingras_csc', 'Dingras Community Service Center'), ('pangasinan_po', 'Pangasinan Provincial Office'), ('ilocossur_po', 'Ilocos Sur Provincial Office'), ('ilocosnorte_po', 'Ilocos Norte Provincial Office'), ('regional', 'Regional Office')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificateoftravel',
            name='travel_order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
