# Generated by Django 5.2.7 on 2025-10-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0089_aftertravelreport_is_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOfAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_of_appearance', models.FileField(blank=True, null=True, upload_to='liquidations/certificate_of_appearance/')),
                ('is_draft', models.BooleanField(default=False, help_text='True if this is a draft, False if submitted for approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_order', models.ForeignKey(blank=True, help_text='Travel order this draft belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_certificate_of_appearance', to='api1.travelorder')),
            ],
        ),
    ]
