# Generated by Django 5.2.7 on 2025-10-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0090_certificateofappearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='region',
        ),
    ]
