# Generated by Django 5.2.7 on 2025-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0091_remove_itinerary_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount set by accountant during final audit', max_digits=10, null=True),
        ),
    ]
