# Generated by Django 5.2.7 on 2025-11-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0092_liquidation_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='after_travel_report_draft',
            field=models.JSONField(blank=True, default=dict, help_text='Draft data for after travel report', null=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_appearance_draft',
            field=models.JSONField(blank=True, default=dict, help_text='Draft data for certificate of appearance (file path)', null=True),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='certificate_of_travel_draft',
            field=models.JSONField(blank=True, default=dict, help_text='Draft data for certificate of travel', null=True),
        ),
    ]
