# Generated by Django 5.2.7 on 2025-11-04 03:51

import django.db.models.deletion
from django.db import migrations, models


def check_column_exists(cursor, table_name, column_name):
    """Check if a column exists in a table"""
    cursor.execute("""
        SELECT COUNT(*) as count
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = %s
        AND COLUMN_NAME = %s
    """, [table_name, column_name])
    result = cursor.fetchone()
    return result[0] > 0


def add_purpose_specific_role_columns_if_needed(apps, schema_editor):
    """Add purpose_id and specific_role_id columns if they don't exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if purpose_id column exists
        if not check_column_exists(cursor, 'api1_travelorder', 'purpose_id'):
            # Add the column first
            cursor.execute("""
                ALTER TABLE api1_travelorder
                ADD COLUMN purpose_id BIGINT NULL
            """)
            # Then add the foreign key constraint
            try:
                cursor.execute("""
                    ALTER TABLE api1_travelorder
                    ADD CONSTRAINT api1_travelorder_purpose_id_fk
                    FOREIGN KEY (purpose_id) REFERENCES api1_purpose(id)
                    ON DELETE SET NULL
                """)
            except Exception as e:
                # Constraint might already exist, that's okay
                print(f"Note: Could not add purpose_id constraint: {e}")
        
        # Check if specific_role_id column exists
        if not check_column_exists(cursor, 'api1_travelorder', 'specific_role_id'):
            # Add the column first
            cursor.execute("""
                ALTER TABLE api1_travelorder
                ADD COLUMN specific_role_id BIGINT NULL
            """)
            # Then add the foreign key constraint
            try:
                cursor.execute("""
                    ALTER TABLE api1_travelorder
                    ADD CONSTRAINT api1_travelorder_specific_role_id_fk
                    FOREIGN KEY (specific_role_id) REFERENCES api1_specificrole(id)
                    ON DELETE SET NULL
                """)
            except Exception as e:
                # Constraint might already exist, that's okay
                print(f"Note: Could not add specific_role_id constraint: {e}")


def remove_purpose_specific_role_columns(apps, schema_editor):
    """Remove purpose_id and specific_role_id columns"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Drop foreign key constraints first
        try:
            cursor.execute("ALTER TABLE api1_travelorder DROP FOREIGN KEY api1_travelorder_purpose_id_fk")
        except:
            pass
        try:
            cursor.execute("ALTER TABLE api1_travelorder DROP FOREIGN KEY api1_travelorder_specific_role_id_fk")
        except:
            pass
        
        # Drop columns
        try:
            cursor.execute("ALTER TABLE api1_travelorder DROP COLUMN purpose_id")
        except:
            pass
        try:
            cursor.execute("ALTER TABLE api1_travelorder DROP COLUMN specific_role_id")
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0093_liquidation_after_travel_report_draft_and_more'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle existing tables
        migrations.SeparateDatabaseAndState(
            # Database operations: Create tables only if they don't exist
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS api1_purpose (
                            id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            purpose_name VARCHAR(255) NOT NULL,
                            is_archived BOOLEAN NOT NULL DEFAULT FALSE
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS api1_purpose"
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS api1_specificrole (
                            id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            role_name VARCHAR(255) NOT NULL,
                            is_archived BOOLEAN NOT NULL DEFAULT FALSE
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS api1_specificrole"
                ),
            ],
            # State operations: Update Django's migration state
            state_operations=[
                migrations.CreateModel(
                    name='Purpose',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('purpose_name', models.CharField(max_length=255)),
                        ('is_archived', models.BooleanField(default=False)),
                    ],
                ),
                migrations.CreateModel(
                    name='SpecificRole',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('role_name', models.CharField(max_length=255)),
                        ('is_archived', models.BooleanField(default=False)),
                    ],
                ),
            ],
        ),
        # Add foreign key columns if they don't exist
        migrations.RunPython(
            add_purpose_specific_role_columns_if_needed,
            remove_purpose_specific_role_columns
        ),
        # Update Django's state to reflect the ForeignKey fields
        # Use SeparateDatabaseAndState since the columns might already exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations needed - columns already added by RunPython above
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='travelorder',
                    name='purpose',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_orders', to='api1.purpose'),
                ),
                migrations.AlterField(
                    model_name='travelorder',
                    name='specific_role',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_orders', to='api1.specificrole'),
                ),
            ],
        ),
    ]
