# Generated by Django 5.2.7 on 2026-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0095_remove_province_city_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='certificate_of_appearance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('bookkeeper_approved', 'Bookkeeper Approved'), ('bookkeeper_rejected', 'Bookkeeper Rejected'), ('accountant_approved', 'Accountant Approved'), ('accountant_rejected', 'Accountant Rejected')], default='pending', max_length=20),
        ),
    ]
