# Generated by Django 5.2.7 on 2026-03-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0096_alter_liquidation_certificate_of_appearance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateoftravel',
            name='fund_cluster',
            field=models.CharField(blank=True, choices=[('01-RF', '01-RF'), ('07-TF', '07-TF')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='fund_cluster',
            field=models.CharField(blank=True, choices=[('01-RF', '01-RF'), ('07-TF', '07-TF')], max_length=10),
        ),
    ]
