# Generated by Django 5.2.7 on 2026-03-17 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0098_update_fund_cluster_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateoftravel',
            name='recommending_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_of_travel_recommending', to=settings.AUTH_USER_MODEL),
        ),
    ]
